package com.example.newproject

import java.text.SimpleDateFormat
import java.util.Locale

// 補記メモの生成結果を検証し、保存用Markdownへ整形する純粋ロジック。
// AI呼び出しやファイルI/Oは持たない（AnnotationController が担当）。
internal object AnnotationComposer {

    // メイン（viewModelScope）からのみ使う前提。SimpleDateFormat はスレッド非安全のため
    // 別スレッドから使う場合は都度生成に変えること。
    val DISPLAY_TIMESTAMP_FORMAT = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
    val FILE_TIMESTAMP_FORMAT = SimpleDateFormat("yyyyMMdd_HHmm", Locale.getDefault())

    private val REQUIRED_SECTIONS = listOf("粒度評価", "補記すべき内容")

    // 必須セクションのいずれかに中身があるかを判定する（空応答の保存を防ぐ）。
    fun hasAnnotationBody(generated: String): Boolean =
        REQUIRED_SECTIONS.any { section ->
            generated.substringAfter("## $section", missingDelimiterValue = "")
                .substringBefore("## ")
                .trim()
                .isNotBlank()
        }

    // 保存用Markdownを組み立てる。欠落した必須セクションは空見出しとして補完する。
    // ※ trimIndent 付きテンプレートは使わない。複数行の生成本文（インデント0）を
    //   補間すると共通インデントが0と判定され、ヘッダ行の字下げが残ったまま
    //   保存されていた（4スペース以上は Obsidian でコードブロック扱いになる）。
    fun buildAnnotationMarkdown(
        title: String,
        createdAt: String,
        generatedBody: String
    ): String = buildString {
        appendLine("# $title AI補記メモ")
        appendLine()
        appendLine("> Source: [[$title]]")
        appendLine("> Created: $createdAt")
        appendLine("> Generated by: Obsidian Mind local AI")
        appendLine()
        append(generatedBody.ensureAnnotationSections())
    }

    private fun String.ensureAnnotationSections(): String {
        val normalized = trim()
        val missing = REQUIRED_SECTIONS.filterNot { "## $it" in normalized }
        if (missing.isEmpty()) return normalized
        return buildString {
            append(normalized)
            missing.forEach { section ->
                append("\n\n## ")
                append(section)
                append("\n")
            }
        }.trim()
    }
}
