package com.example.newproject.domain

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

// 補記メモの生成結果を検証し、保存用Markdownへ整形する純粋ロジック。
// AI呼び出しやファイルI/Oは持たない（`AnnotationController` が担当）。
internal object AnnotationComposer {

    // SimpleDateFormat は都度生成する。共有インスタンスには問題が2つあった。
    // ①スレッド非安全（「メインからのみ使う」という前提をコメントで守っていた）
    // ②`Locale.getDefault()` を生成時に焼き付けるため、実行中にロケールが変わっても追従しない
    /** 補記メモの本文に載せる日時。読む人の言語設定に従う。 */
    fun formatDisplayTimestamp(at: Date): String =
        SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(at)

    /**
     * ファイル名に使う日時。**端末のロケールで変わってはいけない**ので固定する。
     *
     * 既定ロケールのままだと、仏暦カレンダーを使うロケール（th-TH等）で `yyyy` が
     * 2569 のような値になる。`AnnotationController` は保存前にこの名前を予測して
     * 突き合わせるため、名前が揺れると同じノートの補記が別物として並ぶ。
     */
    fun formatFileTimestamp(at: Date): String =
        SimpleDateFormat("yyyyMMdd_HHmm", Locale.ROOT).format(at)

    private val REQUIRED_SECTIONS = listOf("粒度評価", "補記すべき内容")

    // 必須セクションのいずれかに中身があるかを判定する（空応答の保存を防ぐ）。
    fun hasAnnotationBody(generated: String): Boolean =
        REQUIRED_SECTIONS.any { section ->
            generated.substringAfter("## $section", missingDelimiterValue = "")
                .substringBefore("## ")
                .trim()
                .isNotBlank()
        }

    // 保存用Markdownを組み立てる。欠落した必須セクションは空見出しとして補完する。
    // ※ trimIndent 付きテンプレートは使わない。複数行の生成本文（インデント0）を
    //   補間すると共通インデントが0と判定され、ヘッダ行の字下げが残ったまま
    //   保存されていた（4スペース以上は Obsidian でコードブロック扱いになる）。
    fun buildAnnotationMarkdown(
        title: String,
        createdAt: String,
        generatedBody: String
    ): String = buildString {
        appendLine("# $title AI補記メモ")
        appendLine()
        appendLine("> Source: [[$title]]")
        appendLine("> Created: $createdAt")
        appendLine("> Generated by: Vigilith AI")
        appendLine()
        append(generatedBody.ensureAnnotationSections())
    }

    private fun String.ensureAnnotationSections(): String {
        val normalized = trim()
        val missing = REQUIRED_SECTIONS.filterNot { "## $it" in normalized }
        if (missing.isEmpty()) return normalized
        return buildString {
            append(normalized)
            missing.forEach { section ->
                append("\n\n## ")
                append(section)
                append("\n")
            }
        }.trim()
    }
}
